Include GCM rule for hardcoded IV/nonce
returntocorp/sgrep-rules pull request #1329
Opened 2021-06-09 08:23 UTC by securingapps

Reusing the same IV/nonce with GCM can make encryption totally useless with the knowledge of one (cleartext,ciphertext) pair (cf https://www.youtube.com/watch?v=r1awgAl90wM)

This is a first basic rule: it only detects hardcoded IVs built from strings.
I have not found how to detect harcoded byte arrays

There is also an INFO rule for manual review each time GCM is detected.

NB: Those rules could be defined for other languages than Java.

2021-06-09 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=1329) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=1329) before we can accept your contribution.<br/><hr/>**Jeremy MATOS** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-rules?pullRequest=1329) it.</sub>

2021-06-11 06:44 UTC, inkz commented
Thank you for your contribution @securingapps !

could you please format your rule with `pre-commit` hook https://github.com/returntocorp/semgrep-rules/blob/develop/CONTRIBUTING.md#pre-commit
and push changes :pray:

2021-06-11 06:45 UTC, inkz requested changes
`pre-commit` formatting missing

2021-06-11 07:55 UTC, securingapps commented
@inkz Thank you for the feedback.
Formatting and tests should be OK now

2021-06-11 07:59 UTC, inkz commented
@securingapps yeah I see, trying to understand if it is possible to highlight code with hardcoded byte arrays also

2021-06-11 08:19 UTC, inkz commented
@securingapps I resubmitted the pull request with a few updates (split the rules into two files) https://github.com/returntocorp/semgrep-rules/pull/1334
and also attached blocking issue which will allow finding hardcoded byte arrays, will update the rule ones the issue is solved
thanks again for your contribution :v:

2021-06-11 08:19 UTC, closed without merging