Warn on multi-line 'message' in semgrep rules
returntocorp/sgrep-rules pull request #1432
Opened 2021-08-22 23:19 UTC by huonw

This adds a rule `yaml/semgrep/multi-line-message` that flags multi-line messages in semgrep rules, identified as suboptimal in #1431. As discussed in #1431, this may actually be better addressed in semgrep itself, rather than a rule/convention.

It also rewrites all existing rules that use `message: |` to use `message: >-` instead (mechanically: `sed -i '' 's/message: |/message: >-/g' **/*.yaml`).

2021-08-22 23:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=1432) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=1432) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-rules?pullRequest=1432) it.</sub>

2021-08-22 23:20 UTC, huonw commented on yaml/semgrep/multi-line-message.yaml
> +      message: "=~/[\\n\\r]/"
I couldn't work out the right escaping to express this as a metavariable-regex, so I've gone with the deprecated string matching syntax instead.

2021-08-27 22:21 UTC, minusworld commented
Cool, thanks! I'm gonna skim over all the changes just to make sure there aren't any adverse effects, then we can get this rule in 👍

2021-08-27 22:29 UTC, minusworld requested changes
Looks like there's a few rules that broke: https://github.com/returntocorp/semgrep-rules/pull/1432/checks?check_run_id=3447556374

2021-08-30 08:22 UTC, huonw commented
Ah, thanks for starting CI. I'll look at fixing those sometime over the next day or two.

2021-08-31 07:42 UTC, huonw commented
I think I've addressed most of them now.

2021-08-31 20:58 UTC, minusworld commented
Huh, weird that `test-develop` is failing. I'll have to investigate further. It's not required but I wanna double-check to make sure it doesn't break things in the next release. Aside from that, this PR is pretty much done. Thanks! 😄

2021-08-31 21:46 UTC, huonw commented
Great! 

I'm sure you'll find this quickly enough, but it looks like other builds are failing with a similar `cp: can't stat '/src/semgrep_runs_output.tar.gz': No such file or directory` error in `test-develop` too, e.g. #1440.

2021-09-02 21:51 UTC, minusworld commented
@huonw OK, we've made some progress here - the ❌ 's are now a result of this branch being out-of-sync with the `develop` branch upstream. If you merge the develop branch in here, I think that will fix the problem. Thanks for your patience 😅

2021-09-03 05:49 UTC, huonw commented
I've merged and updated the messages of a few extra rules that have landed in develop recently.

2021-09-10 23:15 UTC, minusworld approved these changes

2021-09-10 23:15 UTC, merged

2021-09-10 23:16 UTC, minusworld commented
Thanks @huonw !