csharp sqli pattern
returntocorp/sgrep-rules pull request #1464
Opened 2021-09-10 13:28 UTC by gdraperi

Hello,

I have just finished a rule for detecting SQLI in CSharp.

I am not totally satisfied because it seems not detecting when the issue is located in a parameter of a constructor.

I would need help to make it work.

Best,

Gregory

2021-10-29 08:21 UTC, SPoint42 commented
I just test your rules against a whole number of file where I have SQL-I in C#-.NET. Some of them was triggers, some not. I think we need to update the rules to detect more basic SQLI like this file (not detected with this version of th rules) before putting in the repo

```csharp
public string GetNonSensitiveDataById()
{
	using (SqlConnection connection = new SqlConnection(_configuration.GetValue<string>("ConnectionString")))
	{
		connection.Open();
		SqlCommand command = new SqlCommand($"SELECT * FROM NonSensitiveDataTable WHERE Id = {Request.Query["id"]}", connection);
		using (var reader = command.ExecuteReader())
		{
			if (reader.Read())
			{
				string returnString = string.Empty;
				returnString += $"Name : {reader["Name"]}. ";
				returnString += $"Description : {reader["Description"]}";
				return returnString;
			}
			else
			{
				return string.Empty;
			}
		}
	}
}

```
I just got the capability to audit some CSharp project and will see how to improove your rules

2021-10-29 10:35 UTC, gdraperi commented
Hello, thanks for the feedback. I agree. My corpus was small so I started with a small subset of patterns. Tell me how you want to proceed.

2021-10-29 12:43 UTC, SPoint42 commented
I update your yaml file and seems to work on my sample and yours.

2021-10-29 12:43 UTC, SPoint42 requested changes

2021-10-29 12:43 UTC, SPoint42 commented on csharp/lang/security/sqli/csharp_sqli.yaml
> +
add this here : 

```suggestion
- pattern-not-inside: |
          ...
          $S.Parameters
```

2021-10-29 12:43 UTC, SPoint42 commented on csharp/lang/security/sqli/csharp_sqli.yaml
> +        }
```suggestion
           }
       - pattern: |
              $PATTERN $S = new $PATTERN(...);
```

2021-10-29 13:36 UTC, SPoint42 requested changes

2021-10-29 13:36 UTC, SPoint42 commented on csharp/lang/security/sqli/csharp_sqli.yaml
> +  severity: WARNING
```suggestion
  severity: ERROR
    metadata:
    owasp: 'A1: Injection'
    cwe: >-
      CWE-89: Improper Neutralization of Special Elements used in an SQL
      Command ('SQL Injection')
```

2021-11-09 10:32 UTC, gdraperi commented on csharp/lang/security/sqli/csharp_sqli.yaml
> +  severity: WARNING
Thanks for the feedback. I added all your suggestions. Really appreciated.

2021-11-09 10:55 UTC, gdraperi commented
Hello ,

The pre-commits works now but it seems the others actions fail.

The error message is quite obscure and I am not sure I can do something

```
Error: ROR] `/root/.local/bin/semgrep --skip-unknown-extensions --disable-nosem --json --autofix --dryrun --time --config yaml/semgrep/duplicate-id.yaml --config yaml/semgrep/duplicate-pattern.yaml --config yaml/semgrep/unsatisfiable.yaml --config yaml/semgrep/metadata-cwe.yaml --config yaml/semgrep/metadata-owasp.yaml --config yaml/semgrep/metadata-references.yaml --config yaml/semgrep/empty-message.yaml --config yaml/semgrep/missing-message-field.yaml --config yaml/semgrep/missing-language-field.yaml --config yaml/semgrep/metadata-technology.yaml --config yaml/semgrep/metadata-category.yaml --config yaml/semgrep/multi-line-message.yaml --config yaml/semgrep/slow-pattern-top-ellipsis.yaml --enable-metrics --debug -o /tmp/tmp0b2etp0z csharp/lang/security/sqli/csharp_sqli.cs csharp/lang/security/sqli/csharp_sqli.yaml` failed with exit code 2

This is an internal error, please file an issue at https://github.com/returntocorp/semgrep-action/issues/new/choose
and include any log output from above.
```

2021-11-16 16:30 UTC, minusworld commented
OK, thanks. Let me take a look.

2021-11-16 17:49 UTC, minusworld approved these changes

2021-11-16 17:50 UTC, minusworld commented
@gdraperi @SPoint42 Thanks to you both! Merging this in. If there are issues with it going forward, feel free to open a new PR with changes.

Thanks again!! :D

2021-11-16 17:50 UTC, merged