converting terraform generic iam rules to hcl
returntocorp/sgrep-rules pull request #1494
Opened 2021-09-28 21:38 UTC by colleend

2021-09-29 01:35 UTC, inkz commented on terraform/lang/security/iam/no-iam-data-exfiltration.yaml
> +    technology:
is it possible to add CWE number here?
(I would propose smth like https://cwe.mitre.org/data/definitions/200.html, but you know better)

2021-09-29 01:40 UTC, inkz requested changes
add CWE numbers to some rules (e.g. `no-iam-data-exfiltration`, `no-iam-priv-esc-funcs`)

if it actually make sense to do it :v:, because rules are IaC related maybe it is not applicable

2021-09-29 08:48 UTC, aryx reviewed
Woohoo!

2021-09-29 19:00 UTC, colleend commented
sounds good, I can look into it and add the appropriate CWE #s to some of the rules!

2021-09-30 21:07 UTC, minusworld approved these changes

2021-10-01 02:23 UTC, inkz approved these changes
lgtm!

2021-10-01 15:57 UTC, merged