Spoint42/develop
returntocorp/sgrep-rules pull request #1707
Opened 2022-01-09 16:30 UTC by SPoint42

2022-01-10 08:02 UTC, SPoint42 commented
work on 0.77....
@minusworld ; qhat the hell on this error of unit tests ?

2022-01-10 21:25 UTC, minusworld commented on csharp/lang/security/crypto/random.cs
> +var rnd = new Random();
It looks like this line is missing the `// ruleid:` test annotation. This is probably the cause of the CI failures.

2022-01-10 22:31 UTC, minusworld requested changes
I think there just needs to be a test annotation on the new rule's test file.

Also, it looks like there are a bunch of old commits that are also in this PR. Would you mind updating this PR to branch from the latest `develop` branch on semgrep-rules?

You can add the original repo as an upstream remote and pull in the latest changes. Then branch off that and add the new rule. As it is now, I'm worried about overwriting more recent changes with the old commits.

Thanks! Let me know if you have any questions.

2022-01-27 06:29 UTC, SPoint42 commented
I will have a look to your comments

2022-04-06 17:09 UTC, closed without merging