Leland rails rules
returntocorp/sgrep-rules pull request #1748
Opened 2022-01-25 02:17 UTC by lejliu

2022-01-26 18:42 UTC, colleend commented
Would you mind adding the brakeman link (such as https://github.com/presidentbeef/brakeman/blob/main/lib/brakeman/checks/check_header_dos.rb) as a `source-rule-url` in metadata?) (You can reference this here: https://github.com/returntocorp/semgrep-rules/commit/2cc7a752dcf62ab7a6bce35d3c2feff8e48ecc1a)

2022-01-26 18:58 UTC, colleend requested changes
Thanks for doing this!

2022-01-26 18:58 UTC, colleend commented on ruby/rails/security/audit/rails-check-page-caching-cve.yaml
> +rules:
For this rule, we also want a ruby rule that catches instances of code like 
```
class BooksController < ApplicationController
caches_page :show
end
```
(where show is vulnerable).
Good work on catching the page-caching gems though 👍

2022-01-26 18:58 UTC, colleend commented on ruby/rails/security/audit/rails-check-render-dos.yaml
> +rules:
same for this one: we would also want to catch cases of `render :text` 👍

2022-01-26 18:58 UTC, colleend commented on ruby/rails/security/audit/rails-check-response-splitting.yaml
> +  - id: rails-check-response-splitting
nice!

2022-01-26 18:58 UTC, colleend commented on ruby/rails/security/injection/rails-check-json-parsing-rce.yaml
> +rules:
this one is only for CVE-2013-0333 and not for CVE-2013-0269 right?

2022-01-26 19:14 UTC, lejliu commented on ruby/rails/security/injection/rails-check-json-parsing-rce.yaml
> +rules:
Yes, I'll be working on one for 0269 next when I have time to do more Brakeman rules!

2022-02-02 20:13 UTC, colleend approved these changes
added in the references to brakeman, lgtm!

2022-02-03 21:33 UTC, merged