Leland scala rules
returntocorp/sgrep-rules pull request #1848
Opened 2022-03-01 22:31 UTC by lejliu

Not ready yet. Just making a PR to check GH action results

2022-03-02 03:12 UTC, minusworld commented
So, I'm realizing after looking at this: we had talked about just adding Scala and Kotlin to the language fields for these Java rules, but we won't be able to run tests on them unless they're in the same folder. We'll either have to add the test cases to the Java folder, or create duplicates (or symlinks) of the rules in the appropriate folder.

2022-03-28 21:32 UTC, kurt-r2c requested changes
Failing tests for `gcm-detection`

2022-03-28 21:32 UTC, kurt-r2c commented on scala/lang/security/audit/insecure-random.yaml
> +      Flags the use of a predictable random value from an insecure random number generator. This can lead to vulnerabilities when used
Is this a rule port?  There are non-critical use cases for deterministic random number generators (caching, etc) where `java.util.Random` is acceptable.

2022-03-28 21:32 UTC, kurt-r2c commented on java/lang/security/audit/crypto/gcm-detection.yaml
> +          - pattern: new GCMParameterSpec(...)
This is failing tests:
```
✖ gcm-detection  expected lines: [37, 42, 52, 56], reported lines: [37, 52] 
 test file path: /src/java/lang/security/audit/crypto/gcm-detection.java
```

2022-04-21 03:15 UTC, closed without merging