Make sure $ATTR is filled in with react-http-leak rule
returntocorp/sgrep-rules pull request #1887
Opened 2022-03-11 17:08 UTC by minusworld

2022-03-11 21:43 UTC, colleend commented
@emjin I think the CI `--validate` issues are from a rule that you wrote, can you take a look? 🙏

2022-03-11 21:54 UTC, colleend requested changes

2022-03-11 21:54 UTC, colleend commented on typescript/react/security/audit/react-http-leak.yaml
>                <command icon=... />
we haven't changed this to $EL and $ATTR!

2022-03-11 21:54 UTC, colleend commented on typescript/react/security/audit/react-http-leak.yaml
>                <meta content=... />
haven't changed this either

2022-03-28 20:42 UTC, kurt-r2c commented
@colleend can you recheck this PR for the issue(s) you raised? The force push has messed up the history and the point-in-time commit appears to be missing.

2022-03-28 22:00 UTC, colleend approved these changes
cool, just looked over it again and LGTM!

2022-03-28 22:51 UTC, merged