Argo code injection rule
returntocorp/sgrep-rules pull request #2580
Opened 2022-11-28 13:09 UTC by 0xDC0DE

2022-12-02 15:16 UTC, p4p3r reviewed
I added a couple of comments.
You have linting failures too, make sure you merge develop back into your branch to check if the failures comes from your changes.

2022-12-02 15:16 UTC, p4p3r commented on yaml/argo/security/argo-workflow-parameter-command-injection.yaml
> +      cwe:
You need to add an owasp reference to injection.

2022-12-02 15:16 UTC, p4p3r commented on yaml/argo/security/argo-workflow-parameter-command-injection.yaml
> +            regex: (bash|sh)
I would use a regex more similar to the one here https://github.com/returntocorp/semgrep-rules/blob/develop/python/lang/security/dangerous-subprocess-use.yaml#L114 to match the shell executable.

2022-12-08 15:32 UTC, p4p3r requested changes

2022-12-08 15:32 UTC, p4p3r commented on yaml/argo/security/argo-workflow-parameter-command-injection.test.yaml
> +apiVersion: argoproj.io/v1alpha1
is the `apiVersion` key mandatory? You could add an additional `pattern-inside` to match `argoproj.io` to make sure the rule will report findings only for Argo yaml files.

2022-12-16 09:08 UTC, inkz approved these changes

2022-12-16 14:52 UTC, p4p3r approved these changes
LGTM

2022-12-16 14:52 UTC, merged