Add exception to twitter oath rule for hashes in dependency files
returntocorp/sgrep-rules pull request #2741
Opened 2023-02-22 09:45 UTC by 0xDC0DE

2023-02-22 09:45 UTC, 0xDC0DE commented
Fix for https://github.com/returntocorp/semgrep-rules/issues/2629

2023-02-22 10:34 UTC, LewisArdern commented on generic/secrets/security/detected-twitter-oauth.yaml
> +    - pattern-not-regex: |-
|- ?

2023-02-22 12:14 UTC, LewisArdern requested changes
👍 otherwise

2023-02-23 09:57 UTC, LewisArdern approved these changes
LGTM

2023-02-23 09:57 UTC, merged