Fixup the check-render-local-file-include Ruby rule to be more specific about which parameters can cause LFI or other unintended effects
returntocorp/sgrep-rules pull request #2757
Opened 2023-02-28 14:40 UTC by JackMc

## Link to an issue, if relevant

Hey all! I’m hoping to contribute some noise-reducing fixes upstream for Semgrep Ruby. Specifically, [this rule](https://semgrep.dev/playground/r/ruby.rails.security.brakeman.check-render-local-file-include.check-render-local-file-include?editorMode=advanced) is pretty noisy when run against an example corpus like [Mastodon](https://github.com/mastodon/mastodon). The problem is that the rule looks for params[…] going into any argument to `render`, while most render arguments are harmless. An example would be [this line](https://github.com/mastodon/mastodon/blob/main/app/controllers/api/v2/filters/keywords_controller.rb#L18) which simply renders a user-input-derived value as JSON:

```ryby
@keyword = current_account.custom_filters.find(params[:filter_id]).keywords.create!(resource_params)

render json: @keyword, serializer: REST::FilterKeywordSerializer
```

This PR changes the rule to only match on specific dangerous parameters:

- `inline`: executes arbitrary ERB (RCE)
- `file`: renders the contents file from the filesystem
- `template`: renders a specific template by its descriptor (eg `users/edit`)
- first positional argument: similar to template

Open questions:

- [ ] Do all of these behaviours belong in one rule? 
- [ ] If so, how can we update the description to be more accurate?

### Adding a new rule? Look over this PR checklist

- The issue or PR has links, references, or examples.
- The rule has **true positive** and **true negative** test cases in a file that matches the rule name.

> If the rule is `my-rule`, the test file name should be `my-rule.js`.
>
> True positives are marked by comments with `ruleid: <my-rule>` and true negatives are marked by comments with `ok: <my-rule>`.

- The rule has a good message. A good message includes:

> 1. A description of the pattern (e.g., missing parameter, dangerous flag, out-of-order function calls).
> 1. A description of why this pattern was detected (e.g., logic bug, introduces a security vulnerability, bad practice).
> 1. An alternative that resolves the issue (e.g., use another function, validate data first, discard the dangerous flag).

2023-02-28 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=2757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=2757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-rules?pullRequest=2757) it.</sub>

2023-02-28 14:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=2757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=2757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-rules?pullRequest=2757) it.</sub>

2023-02-28 14:58 UTC, LewisArdern commented
cc @kurt-r2c

2023-03-05 15:36 UTC, JackMc commented
Looks like the CI failed. I think it should be fixed now @LewisArdern, seems like when I was playing with the rule on semgrep.dev it added "-copy" and I forgot to remove that when creating the PR.

2023-03-10 18:35 UTC, kurt-r2c approved these changes

2023-03-10 18:37 UTC, kurt-r2c commented
This is a port of a brakeman rule - I broadly agree with updating this rule to be more opinionated about which arguments are dangerous.

2023-03-10 18:47 UTC, kurt-r2c requested changes
Tests are now failing on develop - @JackMc can you investigate since you did introduce behavior change

2023-03-12 23:25 UTC, JackMc commented
@kurt-r2c I fixed the rule to match the tests (thought I had already changed this, sorry.) I also rebased on origin/develop since the failures on the legacy semgrep tests seem unrelated. They still fail though:

<details>
<summary>Output from legacy tests</summary>
<pre>
~/src/github.com/returntocorp/semgrep-rules % docker run --rm -v $PWD:/src returntocorp/semgrep:1.0.0 semgrep --validate --config /src
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Semgrep rule registry URL is https://semgrep.dev/registry.
Configuration is invalid - found 5 configuration error(s), and 2070 rule(s).
semgrep error: missing keys
  --> /src/stats/cwe_to_metacategory.yml:1
1 | Cryptography:
2 |   - "CWE-523: Unprotected Transport of Credentials"
3 |   - "CWE-319: Cleartext Transmission of Sensitive Information"
4 |   - "CWE-326: Inadequate Encryption Strength"
5 |   - "CWE-327: Use of a Broken or Risky Cryptographic Algorithm"
6 |   - "CWE-329: Not Using a Random IV with CBC Mode"

/src/stats/cwe_to_metacategory.yml_0 is missing `rules` as top-level key

semgrep error: missing keys
  --> /src/stats/metacategory_to_support_tier.yml:1
1 | tier1:
2 |   - CSRF
3 |   - XSS
4 |   - "SQL Injection"
5 |   - "Command Injection"
6 |   - "Code Injection"

/src/stats/metacategory_to_support_tier.yml_0 is missing `rules` as top-level key

semgrep error: missing keys
  --> /src/stats/web_frameworks.yml:1
1 | python:
2 |   - flask
3 |   - django
4 | ruby:
5 |   - rails
6 | golang:

/src/stats/web_frameworks.yml_0 is missing `rules` as top-level key

[ERROR] Semgrep match found when running generic-api-key on /src/generic/secrets/gitleaks/generic-api-key.yaml:
 $1 is used in a 'metavariable-*' conditional or 'focus-metavariable' operator but is never bound by a positive pattern (or is only bound by negative patterns like 'pattern-not')
[ERROR] Semgrep match found when running generic-api-key on /src/generic/secrets/gitleaks/generic-api-key.yaml:
 $1 is used in a 'metavariable-*' conditional or 'focus-metavariable' operator but is never bound by a positive pattern (or is only bound by negative patterns like 'pattern-not')
~/src/github.com/returntocorp/semgrep-rules % docker run --rm -v $PWD:/src returntocorp/semgrep:1.0.0 semgrep --validate --config /src/ruby
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Semgrep rule registry URL is https://semgrep.dev/registry.
Configuration is valid - found 0 configuration error(s), and 113 rule(s).

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
~/src/github.com/returntocorp/semgrep-rules % docker run --rm -v $PWD:/src returntocorp/semgrep:1.0.0 semgrep --validate --config /src/ruby
</pre>
</details>

2023-03-13 18:07 UTC, kurt-r2c commented
@JackMc the historical test failures are a known issue - this is a problem with an older version of Semgrep being overly-opinionated about some patterns while verifying

2023-03-17 22:26 UTC, enncoded approved these changes

2023-03-17 22:26 UTC, kurt-r2c approved these changes

2023-03-17 22:26 UTC, enncoded commented
Thanks for the contribution!

2023-03-17 22:26 UTC, merged