Updates to a few Go rules
returntocorp/sgrep-rules pull request #2849
Opened 2023-04-04 11:37 UTC by 0xDC0DE

2023-04-05 02:32 UTC, inkz approved these changes

2023-04-05 02:34 UTC, inkz submitted a review, later dismissed
all good! :+1:  but looks like there are errors for bot metadata checks and general rules tests

2023-04-12 20:53 UTC, colleend requested changes
Just added a few nits for the messages.

Thank you for doing this work and for adding in the fixes for alot of these rules 🙏

2023-04-12 20:53 UTC, colleend commented on go/lang/security/audit/crypto/bad_imports.yaml
> +    The package is vulnerable to httpoxy attacks (CVE-2015-5386).
could we add a recommendation of a fix 🙏

2023-04-12 20:53 UTC, colleend commented on go/lang/security/audit/crypto/missing-ssl-minversion.yaml
> +    with unsupported an insecure browsers (such as Internet Explorer 10), it may be necessary to enable TLS 1.0 to provide support.
add a line to say 'explicitly set `minversion` to `versionTLS13`?

2023-04-17 07:39 UTC, 0xDC0DE commented
Thanks @colleend, I made the requested changes.

2023-04-18 13:07 UTC, colleend approved these changes
awesome work!!

2023-05-03 00:55 UTC, enncoded approved these changes

2023-05-03 01:02 UTC, merged