Adding XXE rules for SAXParserFactory
returntocorp/sgrep-rules pull request #2907
Opened 2023-05-08 10:43 UTC by coheigea

See https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j
It duplicates the existing DocumentBuilderFactory rules.

2023-05-15 20:02 UTC, colleend requested changes
Thank you for your contribution! As some of these rules are the `documentbuilderfactory` rules with just the metavariable names changed, they will match the same things. I'd recommend just leaving the `saxparserfactory-disallow-doctype-decl-missing` -- thanks for the rules contribution, this is great!

2023-05-15 20:02 UTC, colleend commented on java/lang/security/audit/xxe/saxparserfactory-external-parameter-entities-true.yaml
> +    cwe2021-top25: true
this rule will actually match the same things as https://github.com/returntocorp/semgrep-rules/blob/develop/java/lang/security/audit/xxe/documentbuilderfactory-external-parameter-entities-true.yaml: (https://semgrep.dev/s/55e3) because the metavariable can match anything 👍

2023-05-15 20:02 UTC, colleend commented on java/lang/security/audit/xxe/saxparserfactory-disallow-doctype-decl-false.yaml
> +rules:
same with this rule!: https://semgrep.dev/s/Rd4K

2023-05-15 20:02 UTC, colleend commented on java/lang/security/audit/xxe/saxparserfactory-external-general-entities-true.yaml
> +    This is vulnerable to XML external entity attacks. Disable this by setting the feature "http://xml.org/sax/features/external-general-entities"
same with this rule 👍

2023-05-16 08:49 UTC, coheigea commented
Thanks @colleend for the review. What do you think about changing the existing DocumentBuilderFactory message from:
"DOCTYPE declarations are enabled for this DocumentBuilderFactory."
to something like:
"DOCTYPE declarations are enabled for $DBFACTORY"
Otherwise running the rules on SAXParserFactory instances will report incorrectly that a DocumentBuilderFactory is present. Is there a way to output the class of $DBFACTORY instead?

2023-05-16 17:00 UTC, colleend commented
Great suggestion! That can definitely be done -- metavariables can be used in the messages as well as in the yaml rule pattern, so changing the message to reference the metavariable itself should work 👍 Would you mind removing the duplicate rules and then changing the relevant rule messages? Thank you so much for your contributions! 🙏

2023-05-17 03:35 UTC, coheigea commented
@colleend Please review again, I also added some tests into the existing java classes for SAXParserFactory for the existing rules.

2023-05-17 19:58 UTC, colleend approved these changes
Thank you for your contribution! We appreciate it! It looks good to me.

2023-05-17 20:05 UTC, merged