Adding XXE check for TransformerFactory
returntocorp/sgrep-rules pull request #2921
Opened 2023-05-18 09:18 UTC by coheigea

https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#transformerfactory

One note is that the rule is checking against the XMLConstants.ACCESS_EXTERNAL_STYLESHEET as specified on the OWASP link, and not against the default value of these properties (e.g. "accessExternalStylesheet"). I'm not sure if there is an easy way of doing this without having to duplicate all the rules.

2023-05-18 16:57 UTC, colleend commented
Would you mean cases like `$FACTORY.setAttribute("=~/.*accessExternalStylesheet.*/", "");`? In that case, you could add another `pattern-not-inside` in the rule like 
```
class $C {
      ...
      $V $FACTORY = TransformerFactory.newInstance();
      static {
          ...
          $FACTORY.setAttribute("=~/.*accessExternalStylesheet.*/", "");
          ...
          $FACTORY.setAttribute("=~/.*accessExternalDTD.*/", "");
          ...
      }
      ...
}
```

2023-05-19 10:53 UTC, coheigea commented
OK thanks @colleend , I've added that in

2023-05-19 20:15 UTC, colleend approved these changes
thanks for your contribution!

2023-05-19 20:16 UTC, colleend commented on java/lang/security/audit/xxe/transformerfactory-dtds-not-disabled.java
> +        factory.newTransformer(new StreamSource(xyz));
should be ruleid above this line

2023-05-19 20:18 UTC, colleend commented on java/lang/security/audit/xxe/transformerfactory-dtds-not-disabled.java
> +        factory.newTransformer(new StreamSource(xyz));
'ruleid: ...' should be above this line

2023-05-19 20:19 UTC, colleend requested changes
Would you mind changing the ruleids to be above the lines pointed out? Otherwise our tests won't pass!

2023-05-19 20:19 UTC, colleend commented on java/lang/security/audit/xxe/transformerfactory-dtds-not-disabled.java
> +        factory.newTransformer(new StreamSource(xyz));
//ruleid shoudl be above this line

2023-05-23 21:23 UTC, colleend approved these changes
Thank you for all your hard work! Looks great 👍

2023-05-23 21:23 UTC, merged