pattern-source - fix parameter order = Update ldap-injection.yaml
returntocorp/sgrep-rules pull request #3019
Opened 2023-07-28 17:54 UTC by 1lyasam

Expanding the detection to support vulnerable parameter at any order.
The previous pattern will only match if the vulnerable parameter is the first parameter in the function declaration.
As the vulnerable parameter can be at any place, I added "..." padding before and after

2023-07-28 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=3019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=3019) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: LewisArdern<br/>:x: 1lyasam<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-rules?pullRequest=3019) it.</sub>

2023-07-28 17:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=3019) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-rules?pullRequest=3019) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: LewisArdern<br/>:x: 1lyasam<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-rules?pullRequest=3019) it.</sub>

2023-08-02 16:24 UTC, kurt-r2c requested changes

2023-08-02 16:24 UTC, kurt-r2c commented on csharp/dotnet/security/audit/ldap-injection.yaml
> +    - pattern-inside: $T $M(..,$INPUT,...) {...}
this ellipsis is incomplete
```suggestion
    - pattern-inside: $T $M(...,$INPUT,...) {...}
```

2024-02-12 18:22 UTC, kurt-r2c approved these changes, later dismissed

2024-02-12 18:23 UTC, kurt-r2c commented
@1lyasam please pull in latest or remove pipfile changes from this PR

2024-09-24 13:37 UTC, meenakshisl approved these changes

2025-01-08 09:33 UTC, p4p3r approved these changes
lgtm

2025-01-08 09:33 UTC, merged