elixir: add atom exhausting rule
returntocorp/sgrep-rules pull request #3055
Opened 2023-08-20 17:28 UTC by wingyplus

Detect all Elixir `(String|List).to_atom/1` function calls and fix it with `(String|List).to_existing_atom/1`.

2023-08-21 05:12 UTC, wingyplus commented
Move to correctness category. :)

2023-08-21 22:19 UTC, colleend commented on elixir/lang/correctness/atom-exhaustion.yaml
> +      Atom doesn't garbage by the Garbage Collector. Creating it dynamically with `String.to_atom/1` or `List.to_atom/1` can possible memory leaks if the input cannot control.
```suggestion
      Atom values are appended to a global table but never removed. If input is user-controlled, dynamic instantiations such as `String.to_atom` or `List.to_atom` can lead to possible memory leaks. Instead, use `String.to_existing_atom` or `List.to_existing_atom`.
```

2023-08-21 22:19 UTC, colleend requested changes
Thank you for submitting this! Changed the message a bit, but otherwise it looks good to me 👍

2023-08-22 00:28 UTC, wingyplus commented
> Thank you for submitting this! Changed the message a bit, but otherwise it looks good to me 👍

Thank you. The message looks better!

2023-08-22 02:21 UTC, wingyplus commented
@colleend done. :)

2023-08-22 18:13 UTC, colleend approved these changes
lgtm!

2023-08-22 18:23 UTC, merged