elixir: add Elixir Enum best practice
returntocorp/sgrep-rules pull request #3056
Opened 2023-08-21 05:49 UTC by wingyplus

Add 2 rules for Enum:

1. detect and rewrite `Enum.map/2 |> Enum.into/2` into `Enum.into/3`.
2. detect and rewrite `Enum.map/2 |> Enum.join/2` into `Enum.map_join/3`.

2023-08-21 22:13 UTC, colleend requested changes
Thank you for submitting this rule! We really appreciate all contributions. I've left a few comments for mostly formatting issues -- would be great if you could change the PR accordingly!

2023-08-21 22:13 UTC, colleend commented on elixir/lang/best-practice/enum.yaml
> +  - id: enum_map_join
Separate the two rules into 2 files, and separate the related test files too 👍

2023-08-21 22:13 UTC, colleend commented on elixir/lang/best-practice/enum.yaml
> +      Use `Enum.into/3` is more efficient than using `Enum.map/2 |> Enum.into/2`.
```suggestion
      Using `Enum.into/3` is more efficient than using `Enum.map/2 |> Enum.into/2`. 
```

2023-08-21 22:13 UTC, colleend commented on elixir/lang/best-practice/enum.yaml
> +      Use `Enum.map_join/3` is more efficient than using `Enum.map/2 |> Enum.join/2`.
```suggestion
      Using `Enum.map_join/3` is more efficient than using `Enum.map/2 |> Enum.join/2`.
```

2023-08-22 02:27 UTC, wingyplus commented
@colleend done. :)

2023-08-22 18:09 UTC, colleend approved these changes
lgtm! thank you again!

2023-08-22 18:09 UTC, merged