add tainted-exec rule in php
returntocorp/sgrep-rules pull request #3126
Opened 2023-09-23 09:40 UTC by hocnc

Add the tainted-exec rule to detect the command injection vulnerability in PHP

Playground: https://semgrep.dev/playground/s/GG16

2023-10-17 12:41 UTC, 0xDC0DE requested changes
the `.python-version` file should not be part of the PR

2023-10-17 12:44 UTC, 0xDC0DE commented
Thanks for your contribution @hocnc ! This looks like a useful rule. It's using taint mode to find user input flowing into a dangerous sink. I think you could update the metadata to a vuln finding rule instead of an audit type rule.

2023-10-17 12:44 UTC, 0xDC0DE commented on php/lang/security/tainted-exec.yaml
> +    - audit
```suggestion
    - vuln
```

2023-10-18 08:04 UTC, 0xDC0DE commented
I still need you to remove the [python/django/security/injection/path-traversal/.python-version](https://github.com/returntocorp/semgrep-rules/pull/3126/files#diff-d1843446b38ce24d87091282f2d586b2512e5e4c6cd2712d24113729636f4b0b) file before I can approve the PR.

2023-10-18 08:58 UTC, hocnc commented
i did it

2023-10-23 09:03 UTC, 0xDC0DE approved these changes

2023-10-30 04:20 UTC, hocnc commented
Hi @0xDC0DE 

Are there any problems? Why this pull request still is open status ?

Thanks,
Hoc

2023-10-30 07:35 UTC, merged