Add new rule for flask-route-decorator
returntocorp/sgrep-rules pull request #3244
Opened 2023-12-13 15:53 UTC by khanhldt

Wahoo! New published rules with khanhldt.pnbj from @khanhldt.

See [semgrep.dev/s/2ZJ3Y](https://semgrep.dev/s/2ZJ3Y) for more details.

Thanks for your contribution! ❤️

2023-12-13 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/semgrep/semgrep-rules?pullRequest=3244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/semgrep/semgrep-rules?pullRequest=3244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/semgrep/semgrep-rules?pullRequest=3244) it.</sub>

2023-12-13 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/semgrep/semgrep-rules?pullRequest=3244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/semgrep/semgrep-rules?pullRequest=3244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/semgrep/semgrep-rules?pullRequest=3244) it.</sub>

2023-12-21 01:23 UTC, khanhldt commented
I signed the CLA but that message doesn't get resolved for some reason.

2024-01-09 09:02 UTC, 0xDC0DE commented
It looks like Semgrep does not take the order of decorators into account currently: https://semgrep.dev/playground/s/zdLod

While your regex is a nice workaround, I am not sure if it's the best solution. There are other route decorators in Flask besides the `route` decorator, e.g. `delete`, `patch`, `put`, `post`, `get`. These are basically aliases for the `route` decorator that use a different default value for the optional `methods` argument. I think the rule should probably include those as well.

I've annotated a few more things you should change for the CI checks to pass.

2024-01-09 09:04 UTC, 0xDC0DE requested changes

2024-01-09 09:04 UTC, 0xDC0DE commented on python/flask/correctness/flask-route-decorator.py
> +# ok: Only 1 decorator
Semgrep reports this test syntax as a valid rule id. The `ok:` test syntax expects to be followed by a ruleid. If you want to indicate why this is ok, you can do that on a separate line

```suggestion
# Only 1 decorator
# ok: flask-route-decorator
```

2024-01-09 09:04 UTC, 0xDC0DE commented on python/flask/correctness/flask-route-decorator.py
> +# ok: Correct order
Same here

2024-01-09 09:04 UTC, 0xDC0DE commented on python/flask/correctness/flask-route-decorator.py
> +# ok: "func" not "route"
Same here

2024-01-09 09:04 UTC, 0xDC0DE commented on python/flask/correctness/flask-route-decorator.py
> +# ok: Correct order with app
Same here

2024-01-09 09:04 UTC, 0xDC0DE commented on python/flask/correctness/flask-route-decorator.py
> +# ok: 2 routes are independent
Same here

2024-09-26 07:47 UTC, closed without merging