[PHP] Improve Echoed Requests
returntocorp/sgrep-rules pull request #3353
Opened 2024-04-15 02:44 UTC by shellz-n-stuff

## Description
This PR aims two improve the echoed requests PHP injection rule by doing the followings:
1. Splitting out Print and Echo into seperate rules to allow for Fixes/Autofixes
2. Adding additional sanitisation functions to reduce the number of false positives associated with the rules

## Notes
I couldn't find any way to use fix-regex to keep these rules combined but if would love to simplify this if you have any suggestions.

2024-04-15 02:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/semgrep/semgrep-rules?pullRequest=3353) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/semgrep/semgrep-rules?pullRequest=3353) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/semgrep/semgrep-rules?pullRequest=3353) it.</sub>

2024-04-15 03:28 UTC, shellz-n-stuff commented
Arguably isset should also be removed as a sanitisation function.

2024-04-15 21:46 UTC, kurt-r2c commented
@shellz-n-stuff I suspect `isset` is a sanitizer here because the return type is a boolean and standard propagation would consider the return value tainted (which is false, as it's a boolean not the user input)

2024-04-15 22:18 UTC, shellz-n-stuff commented
> @shellz-n-stuff I suspect `isset` is a sanitizer here because the return type is a boolean and standard propagation would consider the return value tainted (which is false, as it's a boolean not the user input)

@kurt-r2c,

I'll update this rule later today to remove isset. I think a pattern like the below would be a fairly common false negative. I can't think of many cases where this would meaningfully increase false positives either

`if(isset($VAR)){ echo $VAR; }`

2024-04-15 23:27 UTC, shellz-n-stuff commented
@kurt-r2c updated 🙏

2024-04-24 04:07 UTC, kurt-r2c requested changes
@shellz-n-stuff removal of `isset` here will cause false positives as the taint must flow *through* the function to the sink to be considered sanitized - the sanitizer is not by side effect here.

without `isset` this will (incorrectly) flag `echo isset($VAR)`
https://semgrep.dev/playground/s/JDold

the correct behavior is:
https://semgrep.dev/playground/s/5rz6W

note that even with the sanitizer we are still flagging line 13 because an *unsanitized* reference of `$VAR` makes it into the sink

Similarly, `empty(...)` should not be removed.

Please revert these changes and this should be good to merge.

2024-04-24 04:14 UTC, shellz-n-stuff commented
> @shellz-n-stuff removal of `isset` here will cause false positives as the taint must flow _through_ the function to the sink to be considered sanitized - the sanitizer is not by side effect here.
> 
> without `isset` this will (incorrectly) flag `echo isset($VAR)` https://semgrep.dev/playground/s/JDold
> 
> the correct behavior is: https://semgrep.dev/playground/s/5rz6W
> 
> note that even with the sanitizer we are still flagging line 13 because an _unsanitized_ reference of `$VAR` makes it into the sink
> 
> Similarly, `empty(...)` should not be removed.
> 
> Please revert these changes and this should be good to merge.

Howdy Kurt,

Happy to make the change, but I think in terms of optimising the rule having this as a valid sanitiser is far more likely to increase false negatives than false positives. 

It strikes me as a fairly common coding convention to check a variable isn't null before echoing it out e.g.:
```php
if(isset($VAR)){ 
  echo "your name is" + $VAR; 
}

Whereas the pattern you described where you are echoing out a function that returns a boolean seems less common/likely. Obviously I'm happy to make the change if you disagree as I firmly believe you're in a better position to assess the noise/data quality of these rules ❤️

2024-04-24 04:22 UTC, kurt-r2c commented
@shellz-n-stuff totally understand your concern - you'll note that in the correct behavior (https://semgrep.dev/playground/s/5rz6W) line 9 is flagged (as it should be) which exercises the `if(isset(...)){...}` pattern you are concerned about.

```php
<?php

function minimalexample() {
    $VAR = $_GET['someval']
    if(isset($VAR)){ 
        // ok: echoed-request
        echo isset($VAR);
        // ruleid: echoed-request
        echo $VAR; 
        //ok: echoed-request
        echo isset($VAR) . "something";
        // ruleid: echoed-request
        echo isset($VAR) . $VAR;
    }

}

```

2024-04-24 05:47 UTC, shellz-n-stuff commented
> @shellz-n-stuff totally understand your concern - you'll note that in the correct behavior with the `isset` sanitizer (https://semgrep.dev/playground/s/5rz6W) line 9 is flagged (as it should be) which exercises the `if(isset(...)){...}` pattern you are concerned about.
> 
> ```
> <?php
> 
> function minimalexample() {
>     $VAR = $_GET['someval']
>     if(isset($VAR)){ 
>         // ok: echoed-request
>         echo isset($VAR);
>         // ruleid: echoed-request
>         echo $VAR; 
>         //ok: echoed-request
>         echo isset($VAR) . "something";
>         // ruleid: echoed-request
>         echo isset($VAR) . $VAR;
>     }
> 
> }
> ```

Wow, so semgrep's taint tracker mode tracks assignment. That's absolutely unreal. I'll fix this now, I'm super interested in how y'all got that to work in pass by value vs pass by reference.

Apologies for my misunderstanding!

2024-04-24 15:59 UTC, kurt-r2c approved these changes

2024-04-24 16:56 UTC, kurt-r2c commented
String interpolation tests are failing - investigating. Not sure why the removal of the parentheses cause this test to start failing.

2024-04-24 20:31 UTC, kurt-r2c submitted a review, later dismissed

2024-04-24 20:31 UTC, kurt-r2c commented on php/lang/security/injection/echoed-request.php
> +   $VAR = $_GET['someval']
typo, missing semicolon - missed this a couple times, causing a parse error 
```suggestion
   $VAR = $_GET['someval'];
```

2024-04-24 20:31 UTC, kurt-r2c commented on php/lang/security/injection/printed-request.php
> +     $VAR = $_GET['someval']
typo, missing semicolon
```suggestion
     $VAR = $_GET['someval'];
```

2024-04-24 20:31 UTC, kurt-r2c commented on php/lang/security/injection/printed-request.php
> +    $VAR = $_GET['someval']
typo, missing semicolon
```suggestion
    $VAR = $_GET['someval'];
```

2024-04-24 20:31 UTC, kurt-r2c commented on php/lang/security/injection/echoed-request.php
> +    $VAR = $_GET['someval']
typo, missing semicolon
```suggestion
    $VAR = $_GET['someval'];
```

2024-04-24 20:47 UTC, shellz-n-stuff commented
Oh good catch. Thank you @kurt-r2c, my apologies!

2024-04-24 22:27 UTC, kurt-r2c approved these changes

2024-04-24 22:27 UTC, merged