Add rule API key in query parameter (OpenAPI Spec)
returntocorp/sgrep-rules pull request #3375
Opened 2024-05-07 11:03 UTC by aabashkin

## New Rule
Language: YAML
Technology: OpenAPI Spec (OAS)
Description: Detects usage of API key in a query parameter

2024-05-08 07:47 UTC, inkz commented
@aabashkin please change this line: https://github.com/semgrep/semgrep-rules/pull/3375/files#diff-7214158271a059d8564ae3a7762e21046aed9e5d68bbe34dd308368e236ea0b2R30

to:

```yaml
      subcategory:
      - vuln
```

2024-05-08 07:47 UTC, inkz requested changes
See message above :)

2024-05-08 11:41 UTC, aabashkin commented
@inkz done!

2024-05-09 02:07 UTC, inkz approved these changes

2024-05-09 02:13 UTC, merged