add python.twilio.security.twiml-injection
returntocorp/sgrep-rules pull request #3385
Opened 2024-05-16 19:44 UTC by Becojo

Inspired by the the talk [_API: Alternate Pathway to Injection_ by Fennix at Northsec 2024](https://nsec.io/session/2024-api-alternate-pathway-to-injection.html), add a rule to detect a code sample in Twilio's documentation that could lead to injection of TwiML.

2024-05-27 02:45 UTC, inkz requested changes

2024-05-27 02:45 UTC, inkz commented on python/twilio/security/twiml-injection.yml
> +      technology: [--no-technology--]
Can you please add technology here? like "twilio", "twiml" etc

2024-05-28 02:15 UTC, inkz approved these changes
Great job, thank you for your contribution. Would love to see the recording of the presentation :smile:

2024-05-28 02:15 UTC, merged

2024-05-28 20:28 UTC, becojo commented
@inkz it's available in this live stream recording starting at ~47:00 https://www.youtube.com/live/YUJu8qkkz-o?feature=shared&t=2824

2024-05-29 01:08 UTC, inkz commented
@becojo awesome, thank you very much :+1: